<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-GORURFBI" ignored="2" name="Test2(failed)" tests="1" failures="1" timestamp="23 Mar 2021 07:23:19 GMT" time="0.034" errors="0">
  <testcase name="tc5" time="0.011" classname="org.login.tester.B1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.login.tester.B1.tc5(B1.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- tc5 -->
  <testcase name="tc4" time="0.0" classname="org.login.tester.B1">
    <ignored/>
  </testcase> <!-- tc4 -->
  <testcase name="tc6" time="0.0" classname="org.login.tester.B1">
    <ignored/>
  </testcase> <!-- tc6 -->
</testsuite> <!-- Test2(failed) -->
