<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-GORURFBI" ignored="2" name="Test(failed)" tests="1" failures="1" timestamp="23 Mar 2021 07:23:19 GMT" time="0.034" errors="0">
  <testcase name="tc2" time="0.011" classname="org.login.tester.A1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.login.tester.A1.tc2(A1.java:15)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- tc2 -->
  <testcase name="tc3" time="0.0" classname="org.login.tester.A1">
    <ignored/>
  </testcase> <!-- tc3 -->
  <testcase name="tc1" time="0.0" classname="org.login.tester.A1">
    <ignored/>
  </testcase> <!-- tc1 -->
</testsuite> <!-- Test(failed) -->
